### ISSUE TITLE
Circular Depenedency in migrations

### ISSUE THREAD

**Issue by saiprasadphadke** [Open-Orange-Button/Orange-Button-ProductRegistry#17]
I recently tried to clone the repo and run this on my local machine after switching to the development branch with the steps mentioned in README.md
I am facing an issue where after running the command `python manage.py migrate` I get the following logs in terminal

> System check identified some issues:
> 
> WARNINGS:
> server.AlternativeIdentifier.Identifier_Value: (mysql.W003) MySQL may not allow unique CharFields to have a max_length > 255.
> 	HINT: See: https://docs.djangoproject.com/en/4.1/ref/databases/#mysql-character-fields
> server.Product.ProdCode_Value: (mysql.W003) MySQL may not allow unique CharFields to have a max_length > 255.
> 	HINT: See: https://docs.djangoproject.com/en/4.1/ref/databases/#mysql-character-fields
> Traceback (most recent call last):
>   File "/Users/saiprasadphadke/Documents/Projects/Sunspec-source/Orange-Button-ProductRegistry/manage.py", line 22, in <module>
>     main()
>   File "/Users/saiprasadphadke/Documents/Projects/Sunspec-source/Orange-Button-ProductRegistry/manage.py", line 18, in main
>     execute_from_command_line(sys.argv)
>   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
>     utility.execute()
>   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/management/__init__.py", line 440, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/management/base.py", line 402, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/management/base.py", line 448, in execute
>     output = self.handle(*args, **options)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/management/base.py", line 96, in wrapped
>     res = handle_func(*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 114, in handle
>     executor = MigrationExecutor(connection, self.migration_progress_callback)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/migrations/executor.py", line 18, in __init__
>     self.loader = MigrationLoader(self.connection)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/migrations/loader.py", line 58, in __init__
>     self.build_graph()
>   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/migrations/loader.py", line 305, in build_graph
>     self.graph.ensure_not_cyclic()
>   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/db/migrations/graph.py", line 284, in ensure_not_cyclic
>     raise CircularDependencyError(
> django.db.migrations.exceptions.CircularDependencyError: server.0001_initial, authtoken.0001_initial, authtoken.0002_auto_20160226_1747, authtoken.0003_tokenproxy

I am running a local instance of MYSQL DB and I have added the .cnf file and accordingly changed the path in settings.py

**Comment by Vishganti** [comment]
@saiprasadphadke I updated some old dependencies 

Please pull this tag https://github.com/Open-Orange-Button/Orange-Button-ProductRegistry/tree/a8dbc6bcf573f4815a7c30da7bd38689d1db966d you should be able to build a container locally and run it using the following commands

docker build -t prodregapp-local .

# Run
docker run -d --name prodregapp-test \
    -p 80:80 \
    -p 8000:8000 \
    prodregapp-local

# Watch logs
docker logs prodregapp-test -f
